/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import { HTMLStencilElement, JSXBase } from '@stencil/core/internal';


export namespace Components {
  interface CryptoView {}
  interface TkInput {
    'placeholder': string;
    'value': string;
  }
}

declare global {


  interface HTMLCryptoViewElement extends Components.CryptoView, HTMLStencilElement {}
  var HTMLCryptoViewElement: {
    prototype: HTMLCryptoViewElement;
    new (): HTMLCryptoViewElement;
  };

  interface HTMLTkInputElement extends Components.TkInput, HTMLStencilElement {}
  var HTMLTkInputElement: {
    prototype: HTMLTkInputElement;
    new (): HTMLTkInputElement;
  };
  interface HTMLElementTagNameMap {
    'crypto-view': HTMLCryptoViewElement;
    'tk-input': HTMLTkInputElement;
  }
}

declare namespace LocalJSX {
  interface CryptoView {}
  interface TkInput {
    'placeholder'?: string;
    'value'?: string;
  }

  interface IntrinsicElements {
    'crypto-view': CryptoView;
    'tk-input': TkInput;
  }
}

export { LocalJSX as JSX };


declare module "@stencil/core" {
  export namespace JSX {
    interface IntrinsicElements {
      'crypto-view': LocalJSX.CryptoView & JSXBase.HTMLAttributes<HTMLCryptoViewElement>;
      'tk-input': LocalJSX.TkInput & JSXBase.HTMLAttributes<HTMLTkInputElement>;
    }
  }
}


